version: "3"
services:
  deploy-frontend:
    container_name: deploy-frontend
    image: kantaroso/game-information-firebase:latest
    tty: true
    ports:
      - 5000:5000
      - 9005:9005
    volumes:
      - ../../../app/vue/front:/usr/src/app
    working_dir: /usr/src/app
  deploy-api:
    container_name: deploy-api
    image: kantaroso/game-information-ibmcloud:latest
    tty: true
    volumes:
      - ../../../app/gin/assets:/usr/src/app/assets
      - ../../../app/gin/commands:/usr/src/app/commands
      - ../../../app/gin/config:/usr/src/app/config
      - ../../../app/gin/controllers:/usr/src/app/controllers
      - ../../../app/gin/debug:/usr/src/app/debug
      - ../../../app/gin/go.mod:/usr/src/app/go.mod
      - ../../../app/gin/go.sum:/usr/src/app/go.sum
      - ../../../app/gin/lib:/usr/src/app/lib
      - ../../../app/gin/main.go:/usr/src/app/main.go
      - ../../../app/gin/manifest.yml:/usr/src/app/manifest.yml
    working_dir: /usr/src/app
