version: "3"
services:
  deploy-frontend:
    container_name: deploy-frontend
    image: kantaroso/game-information-firebase:latest
    tty: true
    ports:
      - 5000:5000
      - 9005:9005
    volumes:
      - ../../../app/vue/front:/usr/src/app
    working_dir: /usr/src/app
