version: "3"
services:
  go:
    container_name: api
    image: golang:1.13.8-alpine3.11
    tty: true
    volumes:
      - ../../app/gin:/go/src/game-information
    ports:
      - 80:8090
    env_file:
      - app.env

  vue:
    container_name: front
    image: kantaroso/game-information-vue-base:latest
    tty: true
    volumes:
      - ../../app/vue:/var/www/
    ports:
      - 8090:8080

  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - ../data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - 8080:80
