version: "3"
services:
  go:
    container_name: api
    image: kantaroso/game-information-go-dev:latest
    tty: true
    volumes:
      - ../../app/gin:/go/src/game-information
    ports:
      - 80:8080
    env_file:
      - app.env
    working_dir: /go/src/game-information

  vue:
    container_name: front
    image: kantaroso/game-information-vue-base:latest
    tty: true
    volumes:
      - ../../app/vue:/var/www/
    ports:
      - 8090:8080
    working_dir: /var/www/front

  mysql:
    container_name: mysql
    image: mysql:5.7
    tty: true
    volumes:
      - ../data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    tty: true
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - 8080:80

  varnish:
    container_name: varnish
    image: varnish:6.6.1-alpine
    ports:
      - 8070:80
    volumes:
      - "../varnish/development/default.vcl:/etc/varnish/default.vcl"
    tmpfs:
      - /var/lib/varnish:exec
    environment:
      - VARNISH_SIZE=100M
      - VARNISH_TTL=600
    command: "-p default_keep=300"
