version: "3"
services:
  go:
    container_name: api
    image: kantaroso/game-information-go-dev:latest
    tty: true
    volumes:
      - ../../app/gin:/go/src/game-information
    ports:
      - 80:80
    env_file:
      - app.env
    working_dir: /go/src/game-information

  go-prod:
    container_name: api-prod
    image: golang:1.24.3-alpine3.21
    tty: true
    volumes:
      - ../../app/gin:/go/src/game-information
    ports:
      - 80:80
    env_file:
      - app.env
      - app.prod.env
    working_dir: /go/src/game-information

  vue:
    container_name: front
    image: kantaroso/game-information-vue-base:latest
    tty: true
    volumes:
      - ../../app/vue:/var/www/
    ports:
      - 8090:8080
    working_dir: /var/www/front

  postgres:
    container_name: postgres
    image: postgres:15
    tty: true
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - 8080:80
    depends_on:
      - postgres

  varnish:
    container_name: varnish
    image: varnish:6.6.1-alpine
    ports:
      - 8070:80
    volumes:
      - "../varnish/development/default.vcl:/etc/varnish/default.vcl"
    tmpfs:
      - /var/lib/varnish:exec
    environment:
      - VARNISH_SIZE=100M
      - VARNISH_TTL=600
    command: "-p default_keep=300"

volumes:
  postgres_data: # 名前付きボリュームの定義