CREATE TABLE master.maker (
  id BIGSERIAL PRIMARY KEY, -- bigint AUTO_INCREMENT NOT NULL, PRIMARY KEY (id) は PostgreSQLでは BIGSERIAL PRIMARY KEY
  name VARCHAR(255) NOT NULL,
  code VARCHAR(255) NOT NULL UNIQUE, -- UNIQUE code_uniq (code) はカラム定義で UNIQUE を追加
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, -- TIMESTAMP WITH TIME ZONE を推奨
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL -- MySQLの ON UPDATE CURRENT_TIMESTAMP はトリガーで実現します
);
