CREATE TABLE master.maker_detail (
  maker_id BIGINT PRIMARY KEY, -- bigint NOT NULL, PRIMARY KEY (maker_id) は PostgreSQLでは BIGINT PRIMARY KEY
  ohp_url VARCHAR(255) NOT NULL,
  twitter_name VARCHAR(255) NOT NULL,
  youtube_channel_id VARCHAR(255) NOT NULL,
  youtube_keywords VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL -- MySQLの ON UPDATE CURRENT_TIMESTAMP はトリガーで実現
);