name: go-ci

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v2
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          cd ${GITHUB_WORKSPACE}
          docker-compose -f infra/docker-compose/docker-compose.yml run --rm go go test -cover local.packages/game-information/lib/domain/...

