name: ci

on: [push]

jobs:
  golang-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v2
      - name: cd workspace
        run: cd ${GITHUB_WORKSPACE}
      - name: test
        run: docker-compose -f infra/docker-compose/docker-compose.yml run --rm go go test -cover local.packages/game-information/lib/domain/...

