name: ci

on: [push]

jobs:
  golang-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v2
      - name: cd workspace
        run: cd ${GITHUB_WORKSPACE}
      - name: cache gomod
        id: gomod_cache_id
        uses: actions/cache@v2
        with:
          path: ./tmp/cache/gomod
          key: ${{ runner.os }}-${REPOSITORY_NAME}-gomod-v2
      - name: gomod download
        if: steps.gomod_cache_id.outputs.cache-hit != 'true'
        run: docker-compose -f ./infra/docker-compose/test/docker-compose.yml run --rm go go mod download
      - name: test
        run: docker-compose -f ./infra/docker-compose/test/docker-compose.yml run --rm go go test -cover local.packages/game-information/lib/domain/...

