name: deploy
on:
  workflow_dispatch:
    inputs:
      backend:
        description: 'backend release'
        default: false
        type: boolean
      frontend:
        description: 'frontend release'
        required: false
        type: boolean
jobs:
  deploy-backend:
    if: ${{ inputs.backend }}
    runs-on: ubuntu-latest
    steps:
      - run: echoo "deploy-backend"
  deploy-frontend:
    if: ${{ !failure() && inputs.frontend }}
    needs: deploy-backend
    runs-on: ubuntu-latest
    steps:
      - run: echo "deploy-frontend"
