name: deploy

on: [workflow_dispatch]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v2
      - name: cd workspace
        run: |
          cd ${GITHUB_WORKSPACE}
          mkdir -p ./tmp/cache/docker
      - name : build
        run : make build-vue-assets-prod
      - name : deploy
        run : docker-compose -f infra/docker-compose/deploy/docker-compose.yml --rm deploy-frontend firebase deploy --only hosting --token $FIREBASE_TOKEN
